6 задание
js-tasks-ru/js-20230407_evgeniy478 pull request #5
Opened 2023-05-04 17:26 UTC by Jino90

2023-05-04 17:28 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-05-04 17:31 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-05-04 19:33 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-05-04 22:40 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +    document.getElementsByClassName("sortable-table__body").item(0).innerHTML = this.sortedData.map(item => this.constructRow(item)).join("");
🔴 please don't do this
так делать нельзя!
нельзя обращаться к `document`, подумайте может есть какой-то альтернативный способ?
к примеру на занятии мы рассматривали подход с subElements

2023-05-04 22:40 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +    let sortingHeader = this.headersConfig.filter(header => header.id === fieldValue)[0];
почему тут `let`?

2023-05-04 22:41 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +      this.sortedData.reverse();
помните применение `reverse` мы уже обсуждали?
сортируйте значения сразу в нужном порядке!

2023-05-04 22:42 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +    let hyperlink = document.createElement('a');
почему `let`?
почему данный эл-т не создан через шаблонную строку, как к примеру `div` на строке 121?

2023-05-04 22:43 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +    let addSpan;
может сделать вот так:
```js
let addSpan = '';
```
поможет ли это избавится от `else`?

2023-05-04 22:44 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +    this.element.style.left = event.clientX + 15 + "px";
может 15 следует вынести в переменную?

2023-05-04 22:45 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +    return Tooltip.instance;
```js
if (Tooltip.instance) {
  return Tooltip.instance
}
```

2023-05-04 22:45 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +    if (this.element) {
А где удаление обработчиков?

2023-05-04 22:46 UTC, dosandk requested changes
посмотрите пожалуйста коменты
в SortableTable удалите обращение к document
в Tooltip добавьте удаление обработчиков событий

2023-05-05 12:03 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-05-05 16:46 UTC, dosandk commented on 07-async-code-fetch-api-part-1/1-column-chart/index.js
> +    setTimeout(this.simulateClick, "1000");
🔴 please don't do this
так делать нельзя!

2023-05-05 16:46 UTC, dosandk commented on 07-async-code-fetch-api-part-1/1-column-chart/index.js
> +        <a class="column-chart__link" href="#">${this.label === "orders" ? "View all" : ""}</a>
шаблон следует хранить отдельно!

2023-05-05 16:47 UTC, dosandk commented on 07-async-code-fetch-api-part-1/1-column-chart/index.js
> +    const formatter = new Intl.NumberFormat('en-US', {
форматирование задается с помощью ф-ции к-ю компонент получает в качестве параметра!
вдруг на не доллары следует отобразить

2023-05-05 16:47 UTC, dosandk commented on 07-async-code-fetch-api-part-1/1-column-chart/index.js
> +    for (let elementsByClassNameElement of document.getElementsByClassName("column-chart")) {
`const`

2023-05-05 16:47 UTC, dosandk commented on 07-async-code-fetch-api-part-1/1-column-chart/index.js
> +      return `<div style="--value: ${value * (50 / max)}" data-tooltip="${percent + "%"}"></div>`;
что такое 50?

2023-05-05 16:47 UTC, dosandk commented on 07-async-code-fetch-api-part-1/1-column-chart/index.js
> +    let max = Object.values(data).reduce(
почему используется `let`?

2023-05-05 16:48 UTC, dosandk commented on 07-async-code-fetch-api-part-1/1-column-chart/index.js
> +    return fetch(url).then(response => response.json());
пожалуйста используйте `fetchJson`

2023-05-05 16:48 UTC, dosandk commented on 07-async-code-fetch-api-part-1/1-column-chart/index.js
> +  simulateClick() {
этого метода тут не должно быть!

2023-05-05 16:48 UTC, dosandk requested changes
пожалуйста внесите правки в решение после разбора домашки!

2023-05-05 20:34 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-05-06 20:07 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-05-06 20:15 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-05-07 17:58 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-05-07 20:21 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-05-07 21:01 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-05-08 09:13 UTC, Jino90 commented on 06-events-practice/2-tooltip/index.js
> +    if (this.element) {
В строчках 57-59. Или нужно внутри условия это сделать?

2023-05-08 09:13 UTC, Jino90 commented on 06-events-practice/2-tooltip/index.js
> +    if (this.element) {
> А где удаление обработчиков?

В строчках 57-59. Или нужно внутри условия это сделать?

2023-05-08 09:39 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-05-08 09:39 UTC, Jino90 commented on 07-async-code-fetch-api-part-1/1-column-chart/index.js
> +        <a class="column-chart__link" href="#">${this.label === "orders" ? "View all" : ""}</a>
> шаблон следует хранить отдельно!

Перевёл в ф-ию template

2023-05-08 09:40 UTC, Jino90 commented on 07-async-code-fetch-api-part-1/1-column-chart/index.js
> +  simulateClick() {
Удалил, теперь данные загружаются после клика по кнопке.

2023-05-08 09:41 UTC, Jino90 commented on 07-async-code-fetch-api-part-1/1-column-chart/index.js
> +    return fetch(url).then(response => response.json());
> пожалуйста используйте `fetchJson`

Исправил

2023-05-08 09:42 UTC, Jino90 commented on 07-async-code-fetch-api-part-1/1-column-chart/index.js
> +    let max = Object.values(data).reduce(
> почему используется `let`?

Заменил на const.

2023-05-08 09:42 UTC, Jino90 commented on 07-async-code-fetch-api-part-1/1-column-chart/index.js
> +      return `<div style="--value: ${value * (50 / max)}" data-tooltip="${percent + "%"}"></div>`;
> что такое 50?

Определил как статичное поле

2023-05-08 09:42 UTC, Jino90 commented on 07-async-code-fetch-api-part-1/1-column-chart/index.js
> +    for (let elementsByClassNameElement of document.getElementsByClassName("column-chart")) {
> `const`

исправил

2023-05-08 09:42 UTC, Jino90 commented on 07-async-code-fetch-api-part-1/1-column-chart/index.js
> +    const formatter = new Intl.NumberFormat('en-US', {
> форматирование задается с помощью ф-ции к-ю компонент получает в качестве параметра! вдруг на не доллары следует отобразить

Спасибо, исправил.

2023-05-08 09:43 UTC, Jino90 commented on 07-async-code-fetch-api-part-1/1-column-chart/index.js
> +    setTimeout(this.simulateClick, "1000");
> 🔴 please don't do this так делать нельзя!

убрал

2023-05-08 13:10 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-05-09 11:10 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +    wrapper.innerHTML = `
лучше отделять шаблоны в собственный метод

2023-05-09 11:11 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +    this.sortedColumn = headersConfig.filter(config => config['sortable'] === true)[0].id;
```js
this.sortedColumn = headersConfig.filter(config => config.sortable))[0].id;
```

2023-05-09 11:13 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +      this.element.getElementsByClassName("sortable-table__body").item(0).innerHTML = this
пожалуйста воспользуйтесь методом getSubElements для получения списка эл-тов которые в дальнейшем будут подлежать обновлению

2023-05-09 11:14 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +      document.getElementsByClassName('sortable-table__sort-arrow').item(0).remove();
🔴 please don't do this
так делать нельзя, нельзя обращаться к `document` из компонента для того что-бы получить ссылку на эл-т внутри текущего компонента

2023-05-09 11:14 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +    headerCells.addEventListener('pointerdown', this.onClick);
👍 good

2023-05-09 11:15 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +  static instance;
👍 good

2023-05-09 11:15 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +  mouseOver = event => {
👍 good

2023-05-09 11:16 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +    document.body.removeEventListener("pointerover", this.mouseOut);
👍 good 
также можно воспользоваться AbortController в качестве альтернативы

2023-05-09 11:17 UTC, dosandk commented on 06-events-practice/3-double-slider/index.js
> +    this.mouseDown = false;
почему некоторые поля, инициализируются между вызовами методов?
если веской причины на то нет, может следует вынести инициализацию этих полей за пределы конструктора, в class-properties?

2023-05-09 11:18 UTC, dosandk commented on 06-events-practice/3-double-slider/index.js
> +    const spanArray = this.element.getElementsByTagName('span');
старайтесь никогда не осуществлять поиск по тегам!
теги могут изменяться при изменении верстки, всегда опирайтесь на классы или дата-атрибуты

2023-05-09 11:20 UTC, dosandk commented on 06-events-practice/3-double-slider/index.js
> +    spanArray[spanArray.length - 1].innerText = this.format(this.initMax);
```js
spanArray.at(-1).innerText
```

2023-05-09 11:21 UTC, dosandk commented on 06-events-practice/3-double-slider/index.js
> +    this.sliderLeft = this.element.getElementsByClassName("range-slider__thumb-left").item(0);
пожалуйста откажитесь от поиска по классам!
сохраните ссылки на эл-ты заранее!
метод getSubElements в этом поможет

2023-05-09 11:21 UTC, dosandk commented on 07-async-code-fetch-api-part-1/1-column-chart/index.js
> +    //setTimeout(this.simulateClick, "1000");
не оставляйте закомменченый код

2023-05-09 11:22 UTC, dosandk commented on 07-async-code-fetch-api-part-1/1-column-chart/index.js
> +        <a class="column-chart__link" href="#">${this.label === "orders" ? "View all" : ""}</a>
👍 good

2023-05-09 11:22 UTC, dosandk commented on 07-async-code-fetch-api-part-1/1-column-chart/index.js
> +          344
что такое 344?

2023-05-09 11:22 UTC, dosandk commented on 07-async-code-fetch-api-part-1/2-sortable-table-v3/index.js
> +    this.url = new URL(BACKEND_URL + "/" + this.urlPrefix);
good 👍

2023-05-09 11:23 UTC, dosandk commented on 07-async-code-fetch-api-part-1/2-sortable-table-v3/index.js
>  export default class SortableTable {
good 👍

2023-05-09 11:23 UTC, dosandk approved these changes
good 👍

2023-05-09 11:24 UTC, merged